{"name": "Проверка получения ошибки при повторном использовании логина для создания курьера", "status": "passed", "description": "Проверяются код и тело ответа.", "start": 1726902689081, "stop": 1726902689897, "uuid": "027a6719-6d77-42c2-96b4-e3db4a9ad4b5", "historyId": "a50dffb96edaa7b41cee6ef11f297095", "testCaseId": "a50dffb96edaa7b41cee6ef11f297095", "fullName": "tests.test_courier_create_acc.TestCourierCreate#test_create_courier_account_login_taken_conflict", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create_acc"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "DESKTOP-I4FH3MC"}, {"name": "thread", "value": "105144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create_acc"}]}